<?php
//Customisation.php
//Stores global variables for use in customising CRM to
//your own business' feel.

//Company Info
$CUS_Company_Name = "Mobile Rapid Response Unit";
$CUS_Company_AddressL1 = "48 N Pleasant Street, Suite B2";
$CUS_Company_AddressL2 = "Amherst, MA 01002";
$CUS_Company_Phone = "(860)484-3466";
$CUS_Company_TaxRate = 6.25 * .01;
$CUS_Company_Website = "www.mrru.us/";
$CUS_Company_CRMRoot = "CRM/";

//Employee Title
//Replace this with your company's title for 
$CUS_Employee_Title = "Agent";
$CUS_Assigned_Employee = "Assigned Agent";

//Customer Title
$CUS_Customer_Title = "Customer";

//Category Name
//How are your company's tasks organized? For repair shops, it might be
//by the type of phone/computer/device that's being repaired. 
$CUS_Category_Name = "Phone Model";
$CUS_Category_Short = "Phone";

//Task Summary
//How should your CRM describe the task summary?
$CUS_Task_Summary = "Problem Summary";
$CUS_Task_Short = "Problem";

//Expenses Title
$CUS_Expenses_Title = "Parts";
?>
